BOARD=agibot
BRANCH=vendor
BUILD_DESKTOP=yes
BUILD_MINIMAL=no
VENDOR="Agibot-Armbian"
MAINTAINER="cennac"
MAINTAINERMAIL="cennac@163.com"
DESKTOP_ENVIRONMENT=xfce
DESKTOP_TIER=mid
KERNEL_CONFIGURE=no
COMPRESS_OUTPUTIMAGE=sha,img
RELEASE=noble
