BOARD=agibot
BRANCH=vendor
BUILD_DESKTOP=no
BUILD_MINIMAL=yes
VENDOR="Agibot-Armbian"
MAINTAINER="cennac"
MAINTAINERMAIL="cennac@163.com"
KERNEL_CONFIGURE=no
PACKAGE_LIST_ADDITIONAL="can-utils"
COMPRESS_OUTPUTIMAGE=sha,img
RELEASE=jammy
