export const confidenceMeta = {
  verified: { label: '在线验证', short: '实机', color: '#39d98a' },
  documented: { label: '资料 / 丝印', short: '资料', color: '#f4b942' },
  unknown: { label: '待原理图或测量确认', short: '待确认', color: '#f06464' },
};

const usbA3Pins = [
  ['1', 'VBUS', '+5 V'], ['2', 'D-', 'USB 2.0'], ['3', 'D+', 'USB 2.0'], ['4', 'GND', '地'],
  ['5', 'SSRX-', 'SuperSpeed 接收-'], ['6', 'SSRX+', 'SuperSpeed 接收+'],
  ['7', 'GND_DRAIN', '高速屏蔽地'], ['8', 'SSTX-', 'SuperSpeed 发送-'], ['9', 'SSTX+', 'SuperSpeed 发送+'],
];
const usbMicroPins = [
  ['1', 'VBUS', '+5 V'], ['2', 'D-', 'USB 数据-'], ['3', 'D+', 'USB 数据+'],
  ['4', 'ID', 'OTG 角色识别'], ['5', 'GND', '地'], ['外壳', 'SHIELD', '屏蔽地'],
];
const usbCUsb2Pins = [
  ['A1/A12/B1/B12', 'GND', '地'], ['A4/A9/B4/B9', 'VBUS', '+5 V / 角色协商'],
  ['A5', 'CC1', '配置通道'], ['B5', 'CC2', '配置通道'],
  ['A6/B6', 'D+', 'USB 2.0 数据+'], ['A7/B7', 'D-', 'USB 2.0 数据-'],
  ['其余', 'SS/SBU', '本板连接关系未证实'],
];

// shape: rj45|usbA|usbC|hdmi|microUsb|header|sma|terminal|connector|boardToBoard|m2|button
// rot: 接口朝向弧度（0=朝板底/+z, π=朝板顶/-z, π/2=朝右/+x, -π/2=朝左/-x）
export const connectors = [
  { id: 'eth', index: 1, name: '双千兆网口', designator: 'J6700 区域', category: '网络', confidence: 'verified',
    position: [-6.35, -4.58], shape: 'rj45', rot: Math.PI, count: 2,
    summary: '两路 1000BASE-T，以 eth0 / eth1 出现在在线系统中。未发现 PoE 供电证据。',
    evidence: ['实机 ip link：eth0、eth1', '设备树：gmac0/gmac1 均为 okay'],
    pinout: [['1','BI_DA+','双向差分对 A+'],['2','BI_DA-','双向差分对 A-'],['3','BI_DB+','双向差分对 B+'],['4','BI_DC+','双向差分对 C+'],['5','BI_DC-','双向差分对 C-'],['6','BI_DB-','双向差分对 B-'],['7','BI_DD+','双向差分对 D+'],['8','BI_DD-','双向差分对 D-']],
    note: '支持 Auto MDI-X；照片不能确定左、右口分别对应 eth0 还是 eth1。' },
  { id: 'hdmi', index: 2, name: 'HDMI 输出', designator: 'J5000', category: '显示', confidence: 'verified',
    position: [-2.8, -4.64], shape: 'hdmi', rot: Math.PI, count: 1,
    summary: 'HDMI0 输出已启用，HDMI1 与 HDMI RX 在当前设备树中禁用。',
    evidence: ['设备树：hdmi@fde80000 = okay', '实机 ALSA：rockchip-hdmi0'],
    pinout: [['1/3','TMDS D2+/-','视频数据 2'],['4/6','TMDS D1+/-','视频数据 1'],['7/9','TMDS D0+/-','视频数据 0'],['10/12','TMDS CLK+/-','像素时钟'],['2/5/8/11','SHIELD','差分对屏蔽'],['13','CEC','消费电子控制'],['14','NC/HEAC','依版本定义'],['15','DDC SCL','显示识别时钟'],['16','DDC SDA','显示识别数据'],['17','GND','DDC/CEC 地'],['18','+5 V','最大电流按 HDMI 规范'],['19','HPD','热插拔检测']] },
  { id: 'usb-host', index: 3, name: 'USB 3.x Type-A 主机口', designator: 'USB83000 + J290x 区域', category: 'USB', confidence: 'verified',
    position: [4.65, -4.64], shape: 'usbA', rot: Math.PI, count: 4,
    summary: '板边共四个蓝色 Type-A。实机枚举出 VL805 USB3 控制器与两组 Genesys USB3.2 四口 Hub。',
    evidence: ['实机：VL805 1106:3483', '实机：Genesys 05e3:0610 / 0620'], pinout: usbA3Pins,
    note: '各物理口到 Bus/Port 的一一对应需插拔设备后读取 sysfs 才能确认。' },
  { id: '4g-typec', index: 4, name: '4G USB-C 口', designator: 'J9200（丝印 4G）', category: 'USB', confidence: 'documented',
    position: [1.52, -4.67], shape: 'usbC', rot: Math.PI, count: 1,
    summary: '丝印明确标为 4G，推定用于外接蜂窝通信模块；当前实机未枚举 4G 设备。',
    evidence: ['PCB 丝印：J9200 / 4G'], pinout: usbCUsb2Pins,
    note: 'USB 角色、供电能力及 SuperSpeed/SBU 是否接出仍需原理图确认。' },
  { id: 'flash', index: 5, name: '系统刷机 USB', designator: 'J2600', category: '调试', confidence: 'verified',
    position: [-7.72, 2.75], shape: 'microUsb', rot: -Math.PI / 2, count: 1,
    summary: '用户已实物确认用于刷机。设备树存在可切换 USB OTG / device 控制器。',
    evidence: ['用户实物确认', '设备树：usbdrd3 OTG'], pinout: usbMicroPins,
    note: '照片中的机械外形更接近 Micro-USB；以 J2600 和用途识别最可靠。' },
  { id: 'ttl-usb', index: 6, name: 'TTL 调试控制台 USB', designator: 'J9304', category: '调试', confidence: 'verified',
    position: [-7.72, 3.95], shape: 'microUsb', rot: -Math.PI / 2, count: 1,
    summary: '用户确认该口用于 TTL 控制台。在线系统通过 UART2/ttyFIQ0 输出调试控制台。',
    evidence: ['用户实物确认', '实机：ttyFIQ0', '内核命令行：console=ttyFIQ0'],
    pinout: [...usbMicroPins, ['内部 TX', 'GPIO0B6 / UART2_TX', 'SoC 侧'], ['内部 RX', 'GPIO0B5 / UART2_RX', 'SoC 侧'], ['串口参数', '1500000 8N1', '设备树 baudrate']],
    note: '外部插座是 USB 接口，不应把 USB 的 D+/D- 当作裸 TTL TX/RX。' },
  { id: 'debug-headers', index: 7, name: 'UART / SWD 调试排针', designator: 'J8901 / J8900', category: '调试', confidence: 'documented',
    position: [-6.82, -3.28], shape: 'header', rot: -Math.PI / 2, count: 2,
    summary: '两个 1×3 排针，针脚文字直接印在 PCB 上。',
    evidence: ['PCB 丝印'],
    pinout: [['J8901-1','GND','按丝印方向'],['J8901-2','RX','接目标 TX'],['J8901-3','TX','接目标 RX'],['J8900-1','GND','地'],['J8900-2','SWDIO','SWD 数据'],['J8900-3','SWCLK','SWD 时钟']],
    note: '逻辑电平未由现有资料证明，连接前应测量，优先按 3.3 V 目标谨慎处理。' },
  { id: 'j2500', index: 8, name: '2×5 调试 / 扩展排针', designator: 'J2500', category: '扩展', confidence: 'unknown',
    position: [-7.62, -1.92], shape: 'header', rot: -Math.PI / 2, count: 1,
    summary: '丝印给出 1/2 与 9/10 的针号方向，但没有信号名。',
    evidence: ['PCB 丝印：J2500，2×5'],
    pinout: [['1–10', '未知', '不可按标准 Cortex 10-pin 直接假定']],
    note: '需要原理图或断电通断测量后才能定义。' },
  { id: 'antennas', index: 9, name: '无线天线座', designator: 'ANT6300 / ANT6301', category: '无线', confidence: 'verified',
    position: [-7.52, 0.08], shape: 'sma', rot: -Math.PI / 2, count: 2,
    summary: '两路 50 Ω 射频天线接口，对应板载 Broadcom 449d 无线模块。',
    evidence: ['实机 PCIe：Broadcom 14e4:449d', '设备树：wireless-wlan / bluetooth'],
    pinout: [['中心针', 'RF', '50 Ω 射频信号'], ['外壳', 'GND', '射频地']],
    note: '不要在未接适配天线时进行高功率发射测试。' },
  { id: 'usb-c-bank', index: 10, name: '底边 USB-C 端口组', designator: 'J3300 / J3400 / J3500 / J3600', category: 'USB', confidence: 'documented',
    position: [-2.55, 4.87], shape: 'usbC', rot: 0, count: 4,
    summary: '四个 USB-C 外设口。实机存在 VIA 与 Genesys 四口 Hub，但每个口的总线映射尚未逐口插拔确认。',
    evidence: ['PCB 丝印', '实机 USB 拓扑'], pinout: usbCUsb2Pins,
    note: '不要假定支持 USB-PD、视频输出或充电输入。' },
  { id: 'fan', index: 11, name: '散热风扇电源', designator: 'J9301', category: '电源', confidence: 'documented',
    position: [-4.55, 3.75], shape: 'terminal', rot: 0, count: 1,
    summary: '两针风扇插座，照片中的红黑线提供极性证据。',
    evidence: ['实物线色与照片'],
    pinout: [['靠板中心侧', 'FAN+', '红线'], ['靠天线侧', 'GND', '黑线']],
    note: '电压值未从设备树或丝印中确认，换风扇前必须实测。' },
  { id: 'power', index: 12, name: '主电源输入', designator: 'J2000', category: '电源', confidence: 'verified',
    position: [7.68, 2.85], shape: 'terminal', rot: Math.PI / 2, count: 1,
    summary: '右侧三针电源座。用户确认中间为正极，靠近"301"电感的一针为负极。',
    evidence: ['用户实物确认', '连接器贴签 X / + / -'],
    pinout: [['远离 301 的外侧针', 'X / 未确认', '不接或控制信号待确认'], ['中间针', 'VIN+', '电源正极'], ['靠近 301 的内侧针', 'GND / VIN-', '电源负极']],
    note: '输入电压与允许电流没有可靠资料，通电前必须从原电源标签或实测确认。' },
  { id: 'speaker', index: 13, name: '立体声扬声器输出', designator: 'J7000 / J7001 区域', category: '音频', confidence: 'verified',
    position: [5.58, 1.16], shape: 'terminal', rot: 0, count: 2,
    summary: 'ACM8625P 立体声 BTL 功放已在线枚举，两个两针座与功放输出区域对应。',
    evidence: ['实机 ALSA：rockchip,acm8625p-codec', '设备树：stereo_btl_48khz'],
    pinout: [['每组针 1', 'SPK+', '桥接功放正端'], ['每组针 2', 'SPK-', '桥接功放负端']],
    note: 'BTL 两端都不是地，禁止把任一扬声器端接 GND；左右声道及正负方向待原理图确认。' },
  { id: 'right-harness', index: 14, name: '右侧主线束座组', designator: 'J7002 / 相邻 2×5', category: '扩展', confidence: 'unknown',
    position: [7.55, 0.15], shape: 'connector', rot: Math.PI / 2, count: 1,
    summary: '右边缘的 2×4 与 2×5 大电流/线束连接器，现有设备树不包含物理连接器针号。',
    evidence: ['PCB 丝印与照片'],
    pinout: [['全部针脚', '未知', '不得仅按附近电源器件推断']],
    note: '优先通过原线束追线、断电通断测试或厂商原理图确认。' },
  { id: 'j9701', index: 15, name: '四针辅助线束座', designator: 'J9701', category: '扩展', confidence: 'unknown',
    position: [7.67, -1.85], shape: 'terminal', rot: Math.PI / 2, count: 1,
    summary: '右上区域 1×4 白色线束座，信号未被设备树命名到物理连接器。',
    evidence: ['PCB 丝印：J9701'],
    pinout: [['1–4', '未知', '待测']] },
  { id: 'aux-top', index: 16, name: '顶部两针辅助座', designator: 'J9303 / J5001', category: '扩展', confidence: 'unknown',
    position: [-0.1, -4.28], shape: 'terminal', rot: Math.PI, count: 2,
    summary: 'HDMI 与 USB 旁的两个两针座。编号可见，但用途和极性没有可靠资料。',
    evidence: ['PCB 丝印：J9303、J5001'],
    pinout: [['各 2 针', '未知', '待测']] },
  { id: 'core', index: 17, name: 'RK3588 核心板连接器', designator: 'CN9800', category: '内部', confidence: 'documented',
    position: [0, 2.72], shape: 'boardToBoard', rot: 0, count: 1,
    summary: 'RK3588 CoreBoard V12 与底板的高密度板对板接口，非用户外设接口。',
    evidence: ['PCB 丝印：CN9800', '新增裸板照片'],
    pinout: [['全部针脚', '未公开', '需要核心板/底板原理图']],
    note: '设备树只能说明启用的控制器，不能还原 CN9800 的物理针号。' },
  { id: 'buttons', index: 18, name: '板载按键组', designator: 'SW8900–SW9201', category: '控制', confidence: 'unknown',
    position: [-6.08, -1.12], shape: 'button', rot: 0, count: 6,
    summary: '六个板载轻触按键。现有资料只确认其中设备树存在 ADC keys，未能逐键对应。',
    evidence: ['PCB 丝印', '设备树：adc-keys'],
    pinout: [['各按键', '功能待确认', '不可按编号猜测']] },
  { id: 'm2-slot', index: 19, name: 'M.2 扩展插槽', designator: 'J8600', category: '扩展', confidence: 'verified',
    position: [2.05, 4.0], shape: 'm2', rot: 0, count: 1,
    summary: '位于 17 号核心板连接器下方的黑色 M.2 插槽。用户根据实物确认该接口用途。',
    evidence: ['用户实物确认', 'PCB 丝印：J8600', '新增裸板照片'],
    pinout: [['全部触点', '待确认', 'Key 类型、PCIe/USB/SATA 总线和电源定义需原理图或测量确认']],
    note: '照片可见长卡固定孔位，但不能仅凭外形确定 Key 类型、支持的卡长或是否支持 NVMe。' },
];

export const liveFacts = [
  ['板卡', 'Rockchip RK3588 AGIBOT MB0002 V2 Board'],
  ['内核', 'Linux 5.10.110 · 2024-05-10'],
  ['网络', 'eth0 UP · eth1 DOWN · 双 GMAC'],
  ['CAN', 'can0 / can1 · Rockchip CAN FD · 99 MHz'],
  ['调试串口', 'UART2 · ttyFIQ0 · 1,500,000 baud'],
  ['无线', 'Broadcom 449d · PCIe 14e4:449d'],
  ['USB 控制器', 'VIA VL805 · PCIe 1106:3483'],
  ['USB Hub', 'Genesys 4-port ×2 · VIA 4-port ×1'],
  ['音频', 'ACM8625P stereo BTL · HDMI0 · DP0'],
  ['存储', 'eMMC 233 GiB · /dev/mmcblk0'],
];

export const pinmuxGroups = [
  { title: 'CAN（当前设备树）', rows: [
    ['can0', 'okay', 'GPIO0C0 / GPIO0B7', '物理线束座待对应'],
    ['can1', 'okay', 'GPIO4B2 / GPIO4B3', '物理线束座待对应'],
    ['can2', 'disabled', 'GPIO3C4 / GPIO3C5', '未启用'],
  ] },
  { title: 'UART（启用项）', rows: [
    ['UART0', 'okay', 'GPIO0C4 / GPIO0C5', 'ttyS0'],
    ['UART1', 'okay', 'GPIO1B7 / GPIO1B6', 'ttyS1'],
    ['UART2', 'FIQ console', 'GPIO0B6 TX / GPIO0B5 RX', 'ttyFIQ0 · 1.5 Mbaud'],
    ['UART3', 'okay', 'GPIO1C0 / GPIO1C1', 'ttyS3'],
    ['UART4', 'okay', 'GPIO1D3 / GPIO1D2', 'ttyS4'],
    ['UART5', 'okay', 'GPIO4D4 / GPIO4D5', 'ttyS5'],
    ['UART6', 'okay', 'GPIO1A0 / GPIO1A1', '蓝牙相关'],
    ['UART7', 'okay', 'GPIO2B4 / GPIO2B5', 'ttyS7'],
    ['UART9', 'okay', 'GPIO3D4 / GPIO3D5', 'ttyS9'],
  ] },
];
